spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tFScSzBwopYuVpehdFT
      secret-key: ptFzE3DxOSMbnNO79TzrE2vFRk6j8U
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: color-anta-mall

  application:
    name: color-third-party

server:
  port: 30000
